### ISSUE TITLE
Error building on FreeBSD

### ISSUE THREAD

**Issue by hosiawak** [ksedgwic/clboss#14]
On FreeBSD 11.3-RELEASE-p11 I downloaded v0.4 and then:

    pkg install libev

(version 4.33 got installed).

Output of `./configure` is [here](https://gist.github.com/hosiawak/6af50fb40bd04d61a6ad7205c173efb6)

[1st error](https://gist.github.com/hosiawak/5afb0c910733fcc70dc2c262bdec1501) after running `gmake`.

Renaming `std::site_t` to `__site_t` in Bitcoin/hash160.hpp fixes this problem

[2nd error](https://gist.github.com/hosiawak/111e5eb0d2d701c0af0ac19d92762515)

Unfortunately I have no idea how to fix this. I'm happy to try whatever you suggest and report back.

**Comment by ZmnSCPxj** [comment]
The `emplace` functions and variants "should" exist in C++11, possibly the compiler or its libraries are not actually C++11 compliant.  Try upgrading?  In general, we can replace the `emplace` functions with its older variants, unless we are using movable-but-not-copyable objects (which we sometimes do, I will have to re-check the code for `emplace` calls.

The first error should be fixed by `#include`ing a proper file that defines `std::size_t`, lemme go fix that...

**Comment by ZmnSCPxj** [comment]
I have tried looking into the FreeBSD compile issue, and saw that some ports of GCC on FreeBSD appear to have problems with C++11 support.  Is `c++` on your system GCC? (you can check by `c++ --version`, if it says "Free Software Foundation" and a bunch of other verbiage about being free software, it is GCC).  The error message you show looks like GCC to me but I could be wrong.  If so, can you try with `clang` (`./configure CXX=clang++`)?`clboss` 0.4 and `master` should compile in `clang`, 0.2 does not because raisins.

From what I can determine, GCC on FreeBSD *might* require a bunch of defines to fully support C++11, I will try to dig further.

**Comment by hosiawak** [comment]
It's using clang:
```
# c++ --version
FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
Target: x86_64-unknown-freebsd11.2
Thread model: posix
InstalledDir: /usr/bin```

**Comment by ZmnSCPxj** [comment]
Thanks.  On review of your second error, it looks like it might be only failing for `std::vector<bool>`.

Looking more deeply, it looks like `std::vector<bool>` is separately defined in C++11 as **not** having `emplace_back` --- that gets defined in C++14.  If so, it probably means I need to include some kind of template shenanigan here in order to use `emplace_back` most of the time **except** for a `bool` return type.  And template shenanigans are always a pain.

Can you try these two programs with a `c++ -std=gnu++11`?

```c++
#include<vector>

int main() {
    auto bools = std::vector<bool>();
    bools.emplace_back(false);
    return *bools.begin() ? 1 : 0;
}
```


```c++
#include<vector>

int main() {
    auto ints = std::vector<int>();
    ints.emplace_back(0);
    return *ints.begin();
}
```

**Comment by hosiawak** [comment]
The first program fails to complie:

```
test1.cpp:5:11: error: no member named 'emplace_back' in 'std::__1::vector<bool, std::__1::allocator<bool> >'
    bools.emplace_back(false);
    ~~~~~ ^
1 error generated.
```

The second compiles fine. The exact same thing happens on Mac OS 10.15.4 btw.

**Comment by ZmnSCPxj** [comment]
Right, seems to be my mistake, `std::vector<bool>` does not have `emplace_back`.  Can you check #17 ?
